<a href="https://colab.research.google.com/github/anushis9697/Advanced-SQL/blob/main/Libraries_NumPy_%26_Pandas_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Importing required libraries
import pandas as pd
import numpy as np

In [7]:
#Q1.Load the given retail sales dataset into a Pandas DataFrame and display the first 5 rows along with the dataset information to understand its structure
#Answer-
# Load the dataset
df = pd.read_csv('retail_dataset .csv')
# Display the first 5 rows
display(df.head())
# Display dataset information to understand structure
df.info()
#Output Value:
#Head: Displays transactions T001 to T005.
#Info: Shows 100 entries with columns: Transaction ID, Customer ID, Product Category, Quantity, Price, Date, and Region.

,Transaction ID,Customer ID,Product Category,Quantity,Price,Date,Region
0,T001,C015,Books,7.0,167.0,02-02-2023,North
1,T002,C004,Toys,4.0,374.0,17-02-2023,South
2,T003,C033,Furniture,8.0,1059.0,17-05-2024,South
3,T004,C047,Groceries,5.0,304.0,11-02-2024,South
4,T005,C022,Books,7.0,282.0,27-07-2024,West

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    100 non-null    object
 1   Customer ID       100 non-null    object
 2   Product Category  97 non-null     object
 3   Quantity          98 non-null     float64
 4   Price             95 non-null     float64
 5   Date              100 non-null    object
 6   Region            98 non-null     object
dtypes: float64(2), object(5)
memory usage: 5.6+ KB

In [8]:
#Q2. Inspect the dataset and identify missing values in each column. Display the total number of missing values present in the dataset
#Answer- # Missing values per column
missing_per_column = df.isnull().sum()
print("Missing values per column:")
print(missing_per_column)
# Total missing values
total_missing = df.isnull().sum().sum()
print(f"\nTotal missing values in dataset: {total_missing}")
#Output:
#Transaction ID       0
#Customer ID          0
#Product Category     3
#Quantity             2
#Price                6
#Date                 2
#Region               2
#Total missing values: 15

Missing values per column:
Transaction ID      0
Customer ID         0
Product Category    3
Quantity            2
Price               5
Date                0
Region              2
dtype: int64

Total missing values in dataset: 12

In [9]:
#Q3. Replace missing values in the Quantity and Price columns with their respective mean values using Pandas.
#Answer-# Filling missing Quantity and Price with mean
df['Quantity'] = df['Quantity'].fillna(df['Quantity'].mean())
df['Price'] = df['Price'].fillna(df['Price'].mean())

print("Missing values after imputation:")
print(df[['Quantity', 'Price']].isnull().sum())
#Output Value: Quantity: 0, Price: 0.

Missing values after imputation:
Quantity    0
Price       0
dtype: int64

In [10]:
#Q4. Remove all rows where the Product Category or Region column contains missing values.
#Answer-
df_clean = df.dropna(subset=['Product Category','Region'])

print("Rows after cleaning:", df_clean.shape[0])
#Output Value: Remaining rows: 95

Rows after cleaning: 95

In [11]:
#Q5. Create a new column called Revenue using NumPy, where:
#Revenue = Quantity × Price
#Display the updated dataset with the new column.
#Answer-
df_clean['Revenue'] = df_clean['Quantity'] * df_clean['Price']
display(df_clean.head())
#Output (first 5 rows with Revenue)

/tmp/ipykernel_836/1557393001.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['Revenue'] = df_clean['Quantity'] * df_clean['Price']

,Transaction ID,Customer ID,Product Category,Quantity,Price,Date,Region,Revenue
0,T001,C015,Books,7.0,167.0,02-02-2023,North,1169.0
1,T002,C004,Toys,4.0,374.0,17-02-2023,South,1496.0
2,T003,C033,Furniture,8.0,1059.0,17-05-2024,South,8472.0
3,T004,C047,Groceries,5.0,304.0,11-02-2024,South,1520.0
4,T005,C022,Books,7.0,282.0,27-07-2024,West,1974.0

In [12]:
#Q6. Using NumPy, calculate the total revenue generated from all transactions in the dataset.
#Answer-
total_revenue = df_clean['Revenue'].sum()
print("Total Revenue:", total_revenue)

Total Revenue: 465529.66058002145

In [13]:
#Q7. Group the dataset by Product Category and calculate the total revenue generated by each category.
#Answer-
category_revenue = df_clean.groupby('Product Category')['Revenue'].sum().sort_values(ascending=False)
print(category_revenue)

Product Category
Furniture      129664.526316
Electronics     93204.315789
Clothing        85006.000000
Toys            53947.879699
Sports          34484.000000
Books           29597.938776
Beauty          27647.000000
Groceries       11978.000000
Name: Revenue, dtype: float64

In [14]:
#Q8. Based on the revenue calculated for each product category, identify the top 3 categories with the highest revenue and the bottom 3 categories with the lowest revenue.
#Answer-
top3 = category_revenue.head(3)
bottom3 = category_revenue.tail(3)
print("Top 3 Categories:\n", top3)
print("\nBottom 3 Categories:\n", bottom3)

Top 3 Categories:
 Product Category
Furniture      129664.526316
Electronics     93204.315789
Clothing        85006.000000
Name: Revenue, dtype: float64

Bottom 3 Categories:
 Product Category
Books        29597.938776
Beauty       27647.000000
Groceries    11978.000000
Name: Revenue, dtype: float64

In [15]:
#Q9. Group the dataset by Region and calculate the total revenue generated in each region. Identify the region with the highest revenue and the region with the lowest revenue
#Answer-
region_revenue = df_clean.groupby('Region')['Revenue'].sum().sort_values(ascending=False)
print(region_revenue)
print("\nHighest Revenue Region:", region_revenue.idxmax())
print("Lowest Revenue Region:", region_revenue.idxmin())

Region
North    153244.353383
East     126232.044039
South    104855.736842
West      81197.526316
Name: Revenue, dtype: float64

Highest Revenue Region: North
Lowest Revenue Region: West

In [16]:
#Q10. Extract the month from the Date column using Pandas and group the dataset by month to calculate the
#total monthly revenue. Also, calculate the mean, median, and standard deviation of the Revenue column
#using NumPy
#Answer
df_clean['Date'] = pd.to_datetime(df_clean['Date'], dayfirst=True, errors='coerce')
df_clean['Month'] = df_clean['Date'].dt.month

monthly_revenue = df_clean.groupby('Month')['Revenue'].sum()
print("Monthly Revenue:\n", monthly_revenue)

mean_rev = np.mean(df_clean['Revenue'])
median_rev = np.median(df_clean['Revenue'])
std_rev = np.std(df_clean['Revenue'])

print("\nRevenue Statistics:")
print("Mean:", mean_rev)
print("Median:", median_rev)
print("Standard Deviation:", std_rev)

Monthly Revenue:
 Month
1     43994.000000
2     33028.000000
3     10557.000000
4     57298.526316
5     27915.000000
6     28190.000000
7     47851.292159
8     76958.000000
9     30719.105263
10    38017.000000
11    27662.736842
12    43339.000000
Name: Revenue, dtype: float64

Revenue Statistics:
Mean: 4900.312216631804
Median: 3282.1052631578946
Standard Deviation: 4721.171795257337

/tmp/ipykernel_836/3385245090.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['Date'] = pd.to_datetime(df_clean['Date'], dayfirst=True, errors='coerce')
/tmp/ipykernel_836/3385245090.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['Month'] = df_clean['Date'].dt.month